### ISSUE TITLE
Failed to download spring dependency when using maven repo (tcljava)

### ISSUE THREAD

**Issue by fjtllc** [cverges/expect4j#17]
I gave the maven repo a try, however my system failed to fetch the tcljava depedency. Is there a way I can get around this?

I was using group/artifact/version
"com.github.cverges.expect4j" % "expect4j" % "1.6",

[error] (*:update) sbt.ResolveException: download failed: net.sourceforge.tcljava#com.springsource.tcl.lang.jacl;1.4.1!com.springsource.tcl.lang.jacl.jar

I naively tried to add the spring source repositories (but i think they are already supposed to be copied to the central maven repository)

**Comment by cverges** [comment]
Marking as closed due to unresponsiveness.  Please re-open if the information requested can be provided.

**Comment by sarathkumarp-altiscale** [comment]
I'm facing the same issue for expect4j-1.6 even after adding the repositories in pom.xml
<dependency>
    <groupId>com.github.cverges.expect4j</groupId>
    <artifactId>expect4j</artifactId>
    <version>1.6</version>
</dependency>

[INFO] Scanning for projects...
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.sourceforge.tcljava:com.springsource.tcl.lang.jacl:jar:1.4.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.669 s
[INFO] Finished at: 2015-07-26T20:57:56+05:30
[INFO] Final Memory: 17M/310M
[INFO] ------------------------------------------------------------------------

**Comment by cverges** [comment]
Can you post your pom.xml file contents?

**Comment by sarathkumarp-altiscale** [comment]
```
<groupId>expect4j-test</groupId>
<artifactId>expect4j-test</artifactId>
<version>1.0</version>
<name>expect4j-test</name>
<dependencies>
    <dependency>
        <groupId>com.github.cverges.expect4j</groupId>
        <artifactId>expect4j</artifactId>
        <version>1.6</version>
    </dependency>
</dependencies>
<repositories>
    <repository>
        <id>com.springsource.repository.bundles.release</id>
        <name>SpringSource Enterprise Bundle Repository - SpringSource Bundle Releases</name>
        <url>http://repository.springsource.com/maven/bundles/release</url>
    </repository>
    <repository>
        <id>com.springsource.repository.bundles.external</id>
        <name>SpringSource Enterprise Bundle Repository - External Bundle Releases</name>
        <url>http://repository.springsource.com/maven/bundles/external</url>
    </repository>
</repositories>
```

</project>

**Comment by sarathkumarp-altiscale** [comment]
Infact, while opening the dependency link  [om.springsource.tcl.lang.jacl-1.4.1](http://mvnrepository.com/artifact/net.sourceforge.tcljava/com.springsource.tcl.lang.jacl/1.4.1) in [expect4j-1.9](http://mvnrepository.com/artifact/com.github.cverges/expect4j/1.9), it throws "404 error" Not Found: /artifact/net.sourceforge.tcljava/com.springsource.tcl.lang.jacl/1.4.1

**Comment by cverges** [comment]
I just reinitialized my local Maven repository and was able to resolve the POM dependencies for JACL 1.4.1.  See below for the URLs.

http://repository.springsource.com/maven/bundles/external/net/sourceforge/tcljava/com.springsource.tcl.lang.jacl/1.4.1/com.springsource.tcl.lang.jacl-1.4.1.pom

http://repository.springsource.com/maven/bundles/external/net/sourceforge/tcljava/com.springsource.tcl.lang/1.4.1/com.springsource.tcl.lang-1.4.1.pom

It is not surprising that the dependency link you mentioned (http://mvnrepository.com/artifact/net.sourceforge.tcljava/com.springsource.tcl.lang.jacl/1.4.1) isn't working.  The JACL 1.4.1 package isn't hosted on mvnrepository.com, so they wouldn't have an auto-generated page for it.  You have to go to SpringSource.com to get the details on the package: http://ebr.springsource.com/repository/app/bundle/version/detail?name=com.springsource.tcl.lang.jacl&version=1.4.1.

Try doing the following as a test:
- Clone the Expect4J repository locally: `git clone https://github.com/cverges/expect4j.git`
- Build the repository: `cd expect4j && mvn package`
- Now try building your project.

Alternatively, you could try specifying the JACL dependency in your own pom.xml.  Note that I don't consider this to be a good fix, just a workaround for the fact that JACL 1.4.1 isn't up on Maven Central.
